### ISSUE TITLE
 Controlling Darwin op2 with a Joystick 

### ISSUE THREAD

**Issue by fvega99** [ROBOTIS-OP/robotis_op_documentation#2]
Hello,

I am trying to control Darwin Op2 with a joystick and I am having trouble figuring out how to read the input data from the controller. I currently have the controller connected to the computer through an application called jstest-gtk, yet I am not sure how to convert these values into if statements in order to control darwin.

**Comment by kdaun** [comment]
Hi, this seems to be the same issue as https://github.com/ROBOTIS-OP/robotis_op_framework/issues/4 . Therefore, I close this one.
